# BAG OF WORDS

In [36]:
#gerekli olan kütüphaneler eklendi
import pandas as pd
import on_islem
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from gensim.models import Word2Vec

In [38]:
df = pd.read_csv("data/nlp.csv",index_col=0)
df.head()

Text
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...
3  9. Baidu Research: Çin'in önde gelen arama mot...
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...

In [40]:
df["Text_2"] = df["Text"].apply(on_islem.pre_processing)
df["Text_2"] = df["Text_2"].apply(on_islem.remove_space)
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2  
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  
1  [veri, analiz, edin, chatgptyi, kullanarak, do...  
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...  
3  [baidu, research, çin, ön, gele, ara, motor, b...  
4  [microsoft, ai, microsoft, yapay, zeka, teknol...

In [41]:
#boş liste kontrolü

df[df["Text_2"].str[0].isnull()]

Text Text_2
194  #hesaplamalısosyalbilimler #computationalsocia...     []
464  #investment #software #technology #tech #innov...     []
544  @barolar #ImageRecognition #SınırlıHafıza #Lim...     []

In [42]:
df_index = df[df["Text_2"].str[0].isnull()].index
df = df.drop(df_index)
df = df.reset_index()
del df["index"]

df[df["Text_2"].str[0].isnull()]

Empty DataFrame
Columns: [Text, Text_2]
Index: []

In [43]:
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2  
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  
1  [veri, analiz, edin, chatgptyi, kullanarak, do...  
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...  
3  [baidu, research, çin, ön, gele, ara, motor, b...  
4  [microsoft, ai, microsoft, yapay, zeka, teknol...

In [44]:
df["Text_2"]

0      [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...
1      [veri, analiz, edin, chatgptyi, kullanarak, do...
2      [öncelik, yapay, zeka, olduğunu, iç, önemli, o...
3      [baidu, research, çin, ön, gele, ara, motor, b...
4      [microsoft, ai, microsoft, yapay, zeka, teknol...
                             ...                        
850    [doğal, dil, işle, alan, yük, lisansdoktor, ya...
851                                   [dogal, dil, isle]
852       [ver, madencilik, doğal, dil, işle, uygulamas]
853    [doğal, dil, işleme, il, ilgil, deney, ola, ya...
854    [hafta, öğrencilik, hayat, kaldık, yer, deva, ...
Name: Text_2, Length: 855, dtype: object

In [45]:
#liste yapısından kurtarıp cümleler haline getirdik
df["Text_3"] = [' '.join(w for w in item) for item in df["Text_2"]]
df

Text   
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3    9. Baidu Research: Çin'in önde gelen arama mot...   
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..                                                 ...   
850  doğal dil işleme alanında yüksek lisans-doktor...   
851                           dogal dil isleme şeyleri   
852  Bir veri madenciliği ve doğal dil işleme uygul...   
853  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
854  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                                Text_2   
0    [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1    [veri, analiz, edin, chatgptyi, kullanarak, do...   
2    [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3    [baidu, research, çin, ön, gele, ara, motor, b...   
4    [microsoft, ai, microsoft, yapay, zeka, teknol...   
..                                                 ...   
850  [doğal, dil, işle, alan, yük, lisansdoktor, ya...   
851                                 [dogal, dil, isle]   
852     [ver, madencilik, doğal, dil, işle, uygulamas]   
853  [doğal, dil, işleme, il, ilgil, deney, ola, ya...   
854  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                                Text_3  
0    yapay zeka nedir işe yarar yapay zeka yz bilgi...  
1    veri analiz edin chatgptyi kullanarak doğal di...  
2    öncelik yapay zeka olduğunu iç önemli olduk kı...  
3    baidu research çin ön gele ara motor baidun ar...  
4    microsoft ai microsoft yapay zeka teknoloji od...  
..                                                 ...  
850  doğal dil işle alan yük lisansdoktor yapa danı...  
851                                     dogal dil isle  
852            ver madencilik doğal dil işle uygulamas  
853  doğal dil işleme il ilgil deney ola yazılımcı ...  
854  hafta öğrencilik hayat kaldık yer deva ediyoru...  

[855 rows x 3 columns]

In [11]:
vectorizer = CountVectorizer()
x = vectorizer.fit_transform(df["Text_3"].tolist())
x

<855x4785 sparse matrix of type '<class 'numpy.int64'>'
	with 16965 stored elements in Compressed Sparse Row format>

In [12]:
print(x.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [13]:
x[0]

<1x4785 sparse matrix of type '<class 'numpy.int64'>'
	with 28 stored elements in Compressed Sparse Row format>

In [14]:
df["Text_4"] = x.toarray().tolist()
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2   
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3   
0  yapay zeka nedir işe yarar yapay zeka yz bilgi...  \
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka olduğunu iç önemli olduk kı...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4  
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

In [15]:
set(x.toarray()[0].tolist())

{0, 1, 2, 3, 4}

vectorizer.vocabulary_.keys()

# TF - IDF

In [16]:
#from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
x = vectorizer.fit_transform(df["Text_3"].tolist())

In [17]:
print(x.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [18]:
set(x.toarray()[0])

{0.0,
 0.03508115658001388,
 0.03685011328026531,
 0.12317029281566404,
 0.1287180325367376,
 0.1293951901484212,
 0.14937145922687903,
 0.15331933006757356,
 0.15474585010773745,
 0.15623579147571884,
 0.1669097751456677,
 0.17386946496025046,
 0.1765523493830673,
 0.19014279446116142,
 0.19978536869856103,
 0.20581084119178317,
 0.21337581377665515,
 0.22232665378265135,
 0.22301838801405474,
 0.2366088330921489,
 0.3162294875300779}

In [19]:
df["Text_5"] = x.toarray().tolist()
df

Text   
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3    9. Baidu Research: Çin'in önde gelen arama mot...   
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..                                                 ...   
850  doğal dil işleme alanında yüksek lisans-doktor...   
851                           dogal dil isleme şeyleri   
852  Bir veri madenciliği ve doğal dil işleme uygul...   
853  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
854  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                                Text_2   
0    [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1    [veri, analiz, edin, chatgptyi, kullanarak, do...   
2    [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3    [baidu, research, çin, ön, gele, ara, motor, b...   
4    [microsoft, ai, microsoft, yapay, zeka, teknol...   
..                                                 ...   
850  [doğal, dil, işle, alan, yük, lisansdoktor, ya...   
851                                 [dogal, dil, isle]   
852     [ver, madencilik, doğal, dil, işle, uygulamas]   
853  [doğal, dil, işleme, il, ilgil, deney, ola, ya...   
854  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                                Text_3   
0    yapay zeka nedir işe yarar yapay zeka yz bilgi...  \
1    veri analiz edin chatgptyi kullanarak doğal di...   
2    öncelik yapay zeka olduğunu iç önemli olduk kı...   
3    baidu research çin ön gele ara motor baidun ar...   
4    microsoft ai microsoft yapay zeka teknoloji od...   
..                                                 ...   
850  doğal dil işle alan yük lisansdoktor yapa danı...   
851                                     dogal dil isle   
852            ver madencilik doğal dil işle uygulamas   
853  doğal dil işleme il ilgil deney ola yazılımcı ...   
854  hafta öğrencilik hayat kaldık yer deva ediyoru...   

                                                Text_4   
0    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
..                                                 ...   
850  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
851  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
852  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
853  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
854  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                                Text_5  
0    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
..                                                 ...  
850  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
851  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
852  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
853  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
854  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  

[855 rows x 5 columns]

In [20]:
len(x.toarray()[0])

4785

# Word2vec

In [21]:
#!pip install gensim
#from gensim.models import Word2Vec

In [23]:
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2   
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3   
0  yapay zeka nedir işe yarar yapay zeka yz bilgi...  \
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka olduğunu iç önemli olduk kı...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4   
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                              Text_5  
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [24]:
model = Word2Vec(sentences = df["Text_2"].tolist(),vector_size=100,window=5,min_count=1)
model.save("data/word2vec.model")

In [25]:
print(model)

Word2Vec<vocab=4796, vector_size=100, alpha=0.025>


In [26]:
words = list(model.wv.index_to_key)
words[0:6]

['dil', 'doğal', 'işle', 'yapay', 'zeka', 'il']

In [27]:
len(words)

4796

In [28]:
model.wv.key_to_index["yapay"]

3

In [29]:
model.wv[3]

array([-0.13374703,  0.16304733,  0.02711609,  0.026596  ,  0.03311867,
       -0.24470988,  0.137974  ,  0.46539998, -0.219647  , -0.14726782,
       -0.05043138, -0.27589658,  0.04887177,  0.1823124 ,  0.08614972,
       -0.14061733,  0.05309311, -0.2671898 , -0.05988726, -0.4162838 ,
        0.07659341, -0.06663593,  0.18054758, -0.12349285, -0.02962017,
        0.01315671, -0.13469167, -0.06592678, -0.11339197,  0.02296686,
        0.29847813, -0.00802349,  0.04690903, -0.27420437, -0.04400096,
        0.21941221,  0.06501894, -0.20108353, -0.14642367, -0.22188239,
        0.01486123, -0.19370914,  0.02178672,  0.02468845,  0.11982726,
       -0.13053977, -0.15650168, -0.09462555,  0.03277638,  0.12642893,
        0.15243624, -0.18286537, -0.10369115, -0.04297416, -0.12823392,
        0.12208936,  0.16338511,  0.02287058, -0.08970495,  0.04927776,
       -0.01860367,  0.02079313, -0.05378401,  0.09776953, -0.18616469,
        0.25194007,  0.04516565,  0.14409986, -0.16965863,  0.20

In [30]:
model.wv.get_vector("yapay")

array([-0.13374703,  0.16304733,  0.02711609,  0.026596  ,  0.03311867,
       -0.24470988,  0.137974  ,  0.46539998, -0.219647  , -0.14726782,
       -0.05043138, -0.27589658,  0.04887177,  0.1823124 ,  0.08614972,
       -0.14061733,  0.05309311, -0.2671898 , -0.05988726, -0.4162838 ,
        0.07659341, -0.06663593,  0.18054758, -0.12349285, -0.02962017,
        0.01315671, -0.13469167, -0.06592678, -0.11339197,  0.02296686,
        0.29847813, -0.00802349,  0.04690903, -0.27420437, -0.04400096,
        0.21941221,  0.06501894, -0.20108353, -0.14642367, -0.22188239,
        0.01486123, -0.19370914,  0.02178672,  0.02468845,  0.11982726,
       -0.13053977, -0.15650168, -0.09462555,  0.03277638,  0.12642893,
        0.15243624, -0.18286537, -0.10369115, -0.04297416, -0.12823392,
        0.12208936,  0.16338511,  0.02287058, -0.08970495,  0.04927776,
       -0.01860367,  0.02079313, -0.05378401,  0.09776953, -0.18616469,
        0.25194007,  0.04516565,  0.14409986, -0.16965863,  0.20

In [31]:
def word2vec(value):
    model = Word2Vec.load("data/word2vec.model")
    bfr_list = []
    bfr_len = len(value)
    
    for k in value:
        bfr = model.wv.key_to_index[k]
        bfr = model.wv[bfr]
        bfr_list.append(bfr)
    
    bfr_list = sum(bfr_list)
    bfr_list = bfr_list/bfr_len
    return bfr_list.tolist()

In [32]:
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2   
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3   
0  yapay zeka nedir işe yarar yapay zeka yz bilgi...  \
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka olduğunu iç önemli olduk kı...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4   
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                              Text_5  
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [33]:
df["Text_6"] = df["Text_2"].apply(word2vec)

In [35]:
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2   
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3   
0  yapay zeka nedir işe yarar yapay zeka yz bilgi...  \
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka olduğunu iç önemli olduk kı...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4   
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                              Text_5   
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  \
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                              Text_6  
0  [-0.0524674691259861, 0.06404899805784225, 0.0...  
1  [-0.042258307337760925, 0.0491604208946228, 0....  
2  [-0.04610990360379219, 0.05807032063603401, 0....  
3  [-0.043603669852018356, 0.05235053598880768, 0...  
4  [-0.060327354818582535, 0.07498586922883987, 0...

In [46]:
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2   
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3  
0  yapay zeka nedir işe yarar yapay zeka yz bilgi...  
1  veri analiz edin chatgptyi kullanarak doğal di...  
2  öncelik yapay zeka olduğunu iç önemli olduk kı...  
3  baidu research çin ön gele ara motor baidun ar...  
4  microsoft ai microsoft yapay zeka teknoloji od...

In [47]:
df["bow"] = on_islem.bag_of_words(df["Text_3"])
df["tfidf"] = on_islem.tfidf(df["Text_3"])
df["word2vec"] = df["Text_2"].apply(on_islem.word2vec)

In [48]:
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2   
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3   
0  yapay zeka nedir işe yarar yapay zeka yz bilgi...  \
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka olduğunu iç önemli olduk kı...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                                 bow   
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                               tfidf   
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  \
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                            word2vec  
0  [-0.0524674691259861, 0.06404899805784225, 0.0...  
1  [-0.042258307337760925, 0.0491604208946228, 0....  
2  [-0.04610990360379219, 0.05807032063603401, 0....  
3  [-0.043603669852018356, 0.05235053598880768, 0...  
4  [-0.060327354818582535, 0.07498586922883987, 0...